#!/bin/bash

PKG_list+=('base-devel')
PKG_list+=('git')
PKG_list+=('wget')
PKG_list+=('sudo')
PKG_list+=('nano')
PKG_list+=('tree')
PKG_list+=('archiso')
PKG_list+=('dhcpcd')
PKG_list+=('iwd')
PKG_list+=('w3m')
PKG_list+=('neofetch')
PKG_list+=('xorg-xdm')
PKG_list+=('xfce4')
PKG_list+=('nnn')
PKG_list+=('figlet')
PKG_list+=('atom')

